name: Build Windows Installer

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install WebView2 SDK
      run: nuget install Microsoft.Web.WebView2 -Version 1.0.1901.177 -OutputDirectory packages

    - name: Configure CMake
      run: cmake -B build -DJUCE_WEBVIEW2_PACKAGE_LOCATION="${{ github.workspace }}/packages"

    - name: Build
      run: cmake --build build --config Release

    - name: Compile Inno Setup Installer
      run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WIDEDIST_Windows_Installer
        path: Output/WIDEDIST_Windows_Installer.exe
